In [2]:
import pandas as pd
from glob import glob
final_file = sorted(glob('output*.csv'))
final_file

['output1.csv', 'output2.csv']

In [5]:
%%time 
merge = pd.concat((pd.read_csv(file) for file in final_file), ignore_index = True)

CPU times: user 7.89 ms, sys: 397 µs, total: 8.28 ms
Wall time: 6.75 ms

In [6]:
merge

,BREADS & CEREALS,Portion size *,per 100 grams (3.5 oz),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 0,Amount
0,Bagel ( 1 average ),140 cals (45g),310 cals,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Biscuit digestives,86 cals (per biscuit),480 cals,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jaffa cake,48 cals (per biscuit),370 cals,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bread white (thick slice),96 cals (1 slice 40g),240 cals,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bread wholemeal (thick),88 cals (1 slice 40g),220 cals,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,15
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,10
292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.0,309
293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,726
294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.0,1664

In [7]:
#creating  a combined CSV
merge.to_csv('merged.csv')